# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

development_category = Category.where(name: 'Development') .first_or_create(name: 'Development')
business_category = Category.where(name: 'Business') .first_or_create(name: 'Business')
itsoftware_category = Category.where(name: 'IT Software') .first_or_create(name: 'IT Software')
office_productivity_category = Category.where(name: 'Office Productivity') .first_or_create(name: 'Office Productivity')
personal_development_category = Category.where(name: 'Personal Development') .first_or_create(name: 'Personal Development')
design_category = Category.where(name: 'Design') .first_or_create(name: 'Design')
marketing_category = Category.where(name: 'Marketing') .first_or_create(name: 'Marketing')
lifestyle_category = Category.where(name: 'Lifestyle') .first_or_create(name: 'Lifestyle')
photography_category = Category.where(name: 'Photography') .first_or_create(name: 'Photography')
health_fitness_category = Category.where(name: 'Health and Fitness') .first_or_create(name: 'Health and Fitness')
teacher_training_category = Category.where(name: 'Teacher Training') .first_or_create(name: 'Teacher Training')
music_category = Category.where(name: 'Music') .first_or_create(name: 'Music')
academics_category = Category.where(name: 'Academics') .first_or_create(name: 'Academics')
language_category = Category.where(name: 'Language') .first_or_create(name: 'Language')


Subcategory.where(name: 'Web Development', category_id: development_category.id).first_or_create(name: 'Web Development', category_id: development_category.id)
Subcategory.where(name: 'Mobile Apps', category_id: development_category.id).first_or_create(name: 'Mobile Apps', category_id: development_category.id)
Subcategory.where(name: 'Programming Languages', category_id: development_category.id).first_or_create(name: 'Programming-Languages', category_id: development_category.id)
Subcategory.where(name: 'Game Development', category_id: development_category.id).first_or_create(name: 'Game Development', category_id: development_category.id)
Subcategory.where(name: 'Databases', category_id: development_category.id).first_or_create(name: 'Databases', category_id: development_category.id)
Subcategory.where(name: 'Software Testing', category_id: development_category.id).first_or_create(name: 'Software Testing', category_id: development_category.id)
Subcategory.where(name: 'Software Engineeringt', category_id: development_category.id).first_or_create(name: 'Software Engineering', category_id: development_category.id)
Subcategory.where(name: 'Development Tools', category_id: development_category.id).first_or_create(name: 'Development Tools', category_id: development_category.id)
Subcategory.where(name: 'E-Commerce', category_id: development_category.id).first_or_create(name: 'E-Commerce', category_id: development_category.id)


Subcategory.where(name: 'Finance', category_id: business_category.id).first_or_create(name: 'Finance', category_id: business_category.id)
Subcategory.where(name: 'Entrepreneurship', category_id: business_category.id).first_or_create(name: 'Entrepreneurship', category_id: business_category.id)
Subcategory.where(name: 'Communications', category_id: business_category.id).first_or_create(name: 'Communications', category_id: business_category.id)
Subcategory.where(name: 'Management', category_id: business_category.id).first_or_create(name: 'Management', category_id: business_category.id)
Subcategory.where(name: 'Sales', category_id: business_category.id).first_or_create(name: 'Sales', category_id: business_category.id)
Subcategory.where(name: 'Strategy', category_id: business_category.id).first_or_create(name: 'Strategy', category_id: business_category.id)
Subcategory.where(name: 'Operations', category_id: business_category.id).first_or_create(name: 'Operations', category_id: business_category.id)
Subcategory.where(name: 'Project Management', category_id: business_category.id).first_or_create(name: 'Project Management', category_id: business_category.id)
Subcategory.where(name: 'Business Law', category_id: business_category.id).first_or_create(name: 'Business Law', category_id: business_category.id)
Subcategory.where(name: 'Data & Analytics', category_id: business_category.id).first_or_create(name: 'Data & Analytics', category_id: business_category.id)
Subcategory.where(name: 'Home Business', category_id: business_category.id).first_or_create(name: 'Home Business', category_id: business_category.id)
Subcategory.where(name: 'Human Resources', category_id: business_category.id).first_or_create(name: 'Human Resources', category_id: business_category.id)
Subcategory.where(name: 'Industry', category_id: business_category.id).first_or_create(name: 'Industry', category_id: business_category.id)
Subcategory.where(name: 'Media', category_id: business_category.id).first_or_create(name: 'Media', category_id: business_category.id)
Subcategory.where(name: 'Real Estate', category_id: business_category.id).first_or_create(name: 'Real Estate', category_id: business_category.id)
Subcategory.where(name: 'Other', category_id: business_category.id).first_or_create(name: 'Other', category_id: business_category.id)

Subcategory.where(name: 'IT Certification', category_id: itsoftware_category.id).first_or_create(name: 'IT Certification', category_id: itsoftware_category.id)
Subcategory.where(name: 'Network & Security', category_id: itsoftware_category.id).first_or_create(name: 'Network & Security', category_id: itsoftware_category.id)
Subcategory.where(name: 'Hardware', category_id: itsoftware_category.id).first_or_create(name: 'Hardware', category_id: itsoftware_category.id)
Subcategory.where(name: 'Operating Systems', category_id: itsoftware_category.id).first_or_create(name: 'Operating Systems', category_id: itsoftware_category.id)
Subcategory.where(name: 'Other', category_id: itsoftware_category.id).first_or_create(name: 'Other', category_id: itsoftware_category.id)


Subcategory.where(name: 'Microsoft', category_id: office_productivity_category.id).first_or_create(name: 'Microsoft', category_id: office_productivity_category.id)
Subcategory.where(name: 'Google', category_id: office_productivity_category.id).first_or_create(name: 'Google', category_id: office_productivity_category.id)
Subcategory.where(name: 'Apple', category_id: office_productivity_category.id).first_or_create(name: 'Apple', category_id: office_productivity_category.id)
Subcategory.where(name: 'SAP', category_id: office_productivity_category.id).first_or_create(name: 'SAP', category_id: office_productivity_category.id)
Subcategory.where(name: 'Intuit', category_id: office_productivity_category.id).first_or_create(name: 'Intuit', category_id: office_productivity_category.id)
Subcategory.where(name: 'Salesforce', category_id: office_productivity_category.id).first_or_create(name: 'Salesforce', category_id: office_productivity_category.id)
Subcategory.where(name: 'Oracle', category_id: office_productivity_category.id).first_or_create(name: 'Oracle', category_id: office_productivity_category.id)
Subcategory.where(name: 'Other', category_id: office_productivity_category.id).first_or_create(name: 'Other', category_id: office_productivity_category.id)

Subcategory.where(name: 'Personal Transformation', category_id: personal_development_category.id).first_or_create(name: 'Personal Transformation', category_id: personal_development_category.id)
Subcategory.where(name: 'Productivity', category_id: personal_development_category.id).first_or_create(name: 'Productivity', category_id: personal_development_category.id)
Subcategory.where(name: 'Leadership', category_id: personal_development_category.id).first_or_create(name: 'Leadership', category_id: personal_development_category.id)
Subcategory.where(name: 'Personal Finance', category_id: personal_development_category.id).first_or_create(name: 'Personal Finance', category_id: personal_development_category.id)
Subcategory.where(name: 'Career Development', category_id: personal_development_category.id).first_or_create(name: 'Career Development', category_id: personal_development_category.id)
Subcategory.where(name: 'Parenting & Relationships', category_id: personal_development_category.id).first_or_create(name: 'Parenting & Relationships', category_id: personal_development_category.id)
Subcategory.where(name: 'Happiness', category_id: personal_development_category.id).first_or_create(name: 'Happiness', category_id: personal_development_category.id)
Subcategory.where(name: 'Religion & Spirituality', category_id: personal_development_category.id).first_or_create(name: 'Religion & Spirituality', category_id: personal_development_category.id)
Subcategory.where(name: 'Personal Brand Building', category_id: personal_development_category.id).first_or_create(name: 'Personal Brand Building', category_id: personal_development_category.id)
Subcategory.where(name: 'Creativity', category_id: personal_development_category.id).first_or_create(name: 'Creativity', category_id: personal_development_category.id)
Subcategory.where(name: 'Influence', category_id: personal_development_category.id).first_or_create(name: 'Influence', category_id: personal_development_category.id)
Subcategory.where(name: 'Self Esteem', category_id: personal_development_category.id).first_or_create(name: 'Self Esteem', category_id: personal_development_category.id)
Subcategory.where(name: 'Stress Management', category_id: personal_development_category.id).first_or_create(name: 'Stress Management', category_id: personal_development_category.id)
Subcategory.where(name: 'Memory & Study Skills', category_id: personal_development_category.id).first_or_create(name: 'Memory & Study Skills', category_id: personal_development_category.id)
Subcategory.where(name: 'Motivation', category_id: personal_development_category.id).first_or_create(name: 'Motivation', category_id: personal_development_category.id)
Subcategory.where(name: 'Other', category_id: personal_development_category.id).first_or_create(name: 'Other', category_id: personal_development_category.id)


Subcategory.where(name: 'Web Design', category_id: design_category.id).first_or_create(name: 'Web Design', category_id: design_category.id)
Subcategory.where(name: 'Graphic Design', category_id: design_category.id).first_or_create(name: 'Graphic Design', category_id: design_category.id)
Subcategory.where(name: 'Design Tools', category_id: design_category.id).first_or_create(name: 'Design Tools', category_id: design_category.id)
Subcategory.where(name: 'User Experience', category_id: design_category.id).first_or_create(name: 'User Experience', category_id: design_category.id)
Subcategory.where(name: 'Game Design', category_id: design_category.id).first_or_create(name: 'Game Design', category_id: design_category.id)
Subcategory.where(name: 'Design Thinking', category_id: design_category.id).first_or_create(name: 'Design Thinking', category_id: design_category.id)
Subcategory.where(name: '3D & Animation', category_id: design_category.id).first_or_create(name: '3D & Animation', category_id: design_category.id)
Subcategory.where(name: 'Fashion', category_id: design_category.id).first_or_create(name: 'Fashion', category_id: design_category.id)
Subcategory.where(name: 'Architectural Design', category_id: design_category.id).first_or_create(name: 'Architectural Design', category_id: design_category.id)
Subcategory.where(name: 'Interior Design', category_id: design_category.id).first_or_create(name: 'Interior Design', category_id: design_category.id)
Subcategory.where(name: 'Other', category_id: design_category.id).first_or_create(name: 'Other', category_id: design_category.id)

Subcategory.where(name: 'Digital Marketing', category_id: marketing_category.id).first_or_create(name: 'Digital Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Search Engine Optimization', category_id: marketing_category.id).first_or_create(name: 'Search Engine Optimization', category_id: marketing_category.id)
Subcategory.where(name: 'Social Media Marketing', category_id: marketing_category.id).first_or_create(name: 'Social Media Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Branding', category_id: marketing_category.id).first_or_create(name: 'Branding', category_id: marketing_category.id)
Subcategory.where(name: 'Marketing Fundamentals', category_id: marketing_category.id).first_or_create(name: 'Marketing Fundamentals', category_id: marketing_category.id)
Subcategory.where(name: 'Analytics & Automation', category_id: marketing_category.id).first_or_create(name: 'Analytics & Automation', category_id: marketing_category.id)
Subcategory.where(name: 'Public Relations', category_id: marketing_category.id).first_or_create(name: 'Public Relations', category_id: marketing_category.id)
Subcategory.where(name: 'Advertising', category_id: marketing_category.id).first_or_create(name: 'Advertising', category_id: marketing_category.id)
Subcategory.where(name: 'Video & Mobile Marketing', category_id: marketing_category.id).first_or_create(name: 'Video & Mobile Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Content Marketing', category_id: marketing_category.id).first_or_create(name: 'Content Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Non-Digital Marketing', category_id: marketing_category.id).first_or_create(name: 'Non-Digital Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Growth Hacking', category_id: marketing_category.id).first_or_create(name: 'Growth Hacking', category_id: marketing_category.id)
Subcategory.where(name: 'Affiliate Marketing', category_id: marketing_category.id).first_or_create(name: 'Affiliate Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Product Marketing', category_id: marketing_category.id).first_or_create(name: 'Product Marketing', category_id: marketing_category.id)
Subcategory.where(name: 'Other', category_id: marketing_category.id).first_or_create(name: 'Other', category_id: marketing_category.id)

Subcategory.where(name: 'Arts & Crafts', category_id: lifestyle_category.id).first_or_create(name: 'Arts & Crafts', category_id: lifestyle_category.id)
Subcategory.where(name: 'Food & Beverage', category_id: lifestyle_category.id).first_or_create(name: 'Food & Beverage', category_id: lifestyle_category.id)
Subcategory.where(name: 'Beauty & Makeup', category_id: lifestyle_category.id).first_or_create(name: 'Beauty & Makeup', category_id: lifestyle_category.id)
Subcategory.where(name: 'Travel', category_id: lifestyle_category.id).first_or_create(name: 'Travel', category_id: lifestyle_category.id)
Subcategory.where(name: 'Gaming', category_id: lifestyle_category.id).first_or_create(name: 'Gaming', category_id: lifestyle_category.id)
Subcategory.where(name: 'Home Improvement', category_id: lifestyle_category.id).first_or_create(name: 'Home Improvement', category_id: lifestyle_category.id)
Subcategory.where(name: 'Pet Care & Training', category_id: lifestyle_category.id).first_or_create(name: 'Pet Care & Training', category_id: lifestyle_category.id)
Subcategory.where(name: 'Other', category_id: lifestyle_category.id).first_or_create(name: 'Other', category_id: lifestyle_category.id)

Subcategory.where(name: 'Digital Photography', category_id: photography_category.id).first_or_create(name: 'Digital Photography', category_id: photography_category.id)
Subcategory.where(name: 'Photography Fundamentals', category_id: photography_category.id).first_or_create(name: 'Photography Fundamentals', category_id: photography_category.id)
Subcategory.where(name: 'Portraits', category_id: photography_category.id).first_or_create(name: 'Portraits', category_id: photography_category.id)
Subcategory.where(name: 'Landscape', category_id: photography_category.id).first_or_create(name: 'Landscape', category_id: photography_category.id)
Subcategory.where(name: 'Black & White', category_id: photography_category.id).first_or_create(name: 'Black & White', category_id: photography_category.id)
Subcategory.where(name: 'Photography Tools', category_id: photography_category.id).first_or_create(name: 'Photography Tools', category_id: photography_category.id)
Subcategory.where(name: 'Mobile Photography', category_id: photography_category.id).first_or_create(name: 'Mobile Photography', category_id: photography_category.id)
Subcategory.where(name: 'Travel Photography', category_id: photography_category.id).first_or_create(name: 'Travel Photography', category_id: photography_category.id)
Subcategory.where(name: 'Commercial Photography', category_id: photography_category.id).first_or_create(name: 'Commercial Photography', category_id: photography_category.id)
Subcategory.where(name: 'Wedding Photography', category_id: photography_category.id).first_or_create(name: 'Wedding Photography', category_id: photography_category.id)
Subcategory.where(name: 'Video Design', category_id: photography_category.id).first_or_create(name: 'Video Design', category_id: photography_category.id)
Subcategory.where(name: 'Other', category_id: photography_category.id).first_or_create(name: 'Other', category_id: photography_category.id)


Subcategory.where(name: 'Fitness', category_id: health_fitness_category.id).first_or_create(name: 'Fitness', category_id: health_fitness_category.id)
Subcategory.where(name: 'General Health', category_id: health_fitness_category.id).first_or_create(name: 'General Health', category_id: health_fitness_category.id)
Subcategory.where(name: 'Sports', category_id: health_fitness_category.id).first_or_create(name: 'Sports', category_id: health_fitness_category.id)
Subcategory.where(name: 'Nutrition', category_id: health_fitness_category.id).first_or_create(name: 'Nutrition', category_id: health_fitness_category.id)
Subcategory.where(name: 'Yoga', category_id: health_fitness_category.id).first_or_create(name: 'Yoga', category_id: health_fitness_category.id)
Subcategory.where(name: 'Mental Health', category_id: health_fitness_category.id).first_or_create(name: 'Mental Health', category_id: health_fitness_category.id)
Subcategory.where(name: 'Dieting', category_id: health_fitness_category.id).first_or_create(name: 'Dieting', category_id: health_fitness_category.id)
Subcategory.where(name: 'Self Defense', category_id: health_fitness_category.id).first_or_create(name: 'Self Defense', category_id: health_fitness_category.id)
Subcategory.where(name: 'Safety & First Aid', category_id: health_fitness_category.id).first_or_create(name: 'Safety & First Aid', category_id: health_fitness_category.id)
Subcategory.where(name: 'Dance', category_id: health_fitness_category.id).first_or_create(name: 'Dance', category_id: health_fitness_category.id)
Subcategory.where(name: 'Meditation', category_id: health_fitness_category.id).first_or_create(name: 'Meditation', category_id: health_fitness_category.id)
Subcategory.where(name: 'Other', category_id: health_fitness_category.id).first_or_create(name: 'Other', category_id: health_fitness_category.id)

Subcategory.where(name: 'Instructional Design', category_id: teacher_training_category.id).first_or_create(name: 'Instructional Design', category_id: teacher_training_category.id)
Subcategory.where(name: 'Educational Development', category_id: teacher_training_category.id).first_or_create(name: 'Educational Development', category_id: teacher_training_category.id)
Subcategory.where(name: 'Teaching Tools', category_id: teacher_training_category.id).first_or_create(name: 'Teaching Tools', category_id: teacher_training_category.id)
Subcategory.where(name: 'Other', category_id: teacher_training_category.id).first_or_create(name: 'Other', category_id: teacher_training_category.id)


Subcategory.where(name: 'Instruments', category_id: music_category.id).first_or_create(name: 'Instruments', category_id: music_category.id)
Subcategory.where(name: 'Production', category_id: music_category.id).first_or_create(name: 'Production', category_id: music_category.id)
Subcategory.where(name: 'Music Fundamentals', category_id: music_category.id).first_or_create(name: 'Music Fundamentals', category_id: music_category.id)
Subcategory.where(name: 'Vocal', category_id: music_category.id).first_or_create(name: 'Vocal', category_id: music_category.id)
Subcategory.where(name: 'Music Techniques', category_id: music_category.id).first_or_create(name: 'Music Techniques', category_id: music_category.id)
Subcategory.where(name: 'Music Software', category_id: music_category.id).first_or_create(name: 'Music Software', category_id: music_category.id)
Subcategory.where(name: 'Other', category_id: music_category.id).first_or_create(name: 'Other', category_id: music_category.id)

Subcategory.where(name: 'Social Science', category_id: academics_category.id).first_or_create(name: 'Social Science', category_id: academics_category.id)
Subcategory.where(name: 'Math & Science', category_id: academics_category.id).first_or_create(name: 'Math & Science', category_id: academics_category.id)
Subcategory.where(name: 'Humanities', category_id: academics_category.id).first_or_create(name: 'Humanities', category_id: academics_category.id)

Subcategory.where(name: 'English', category_id: language_category.id).first_or_create(name: 'English', category_id: language_category.id)
Subcategory.where(name: 'Spanish', category_id: language_category.id).first_or_create(name: 'Spanish', category_id: language_category.id)
Subcategory.where(name: 'German', category_id: language_category.id).first_or_create(name: 'German', category_id: language_category.id)
Subcategory.where(name: 'French', category_id: language_category.id).first_or_create(name: 'French', category_id: language_category.id)
Subcategory.where(name: 'Japanese', category_id: language_category.id).first_or_create(name: 'Japanese', category_id: language_category.id)
Subcategory.where(name: 'Chinese', category_id: language_category.id).first_or_create(name: 'Chinese', category_id: language_category.id)
Subcategory.where(name: 'Russian', category_id: language_category.id).first_or_create(name: 'Russian', category_id: language_category.id)
Subcategory.where(name: 'Latin', category_id: language_category.id).first_or_create(name: 'Latin', category_id: language_category.id)
Subcategory.where(name: 'Arabic', category_id: language_category.id).first_or_create(name: 'Arabic', category_id: language_category.id)
Subcategory.where(name: 'Hebrew', category_id: language_category.id).first_or_create(name: 'Hebrew', category_id: language_category.id)
Subcategory.where(name: 'Italian', category_id: language_category.id).first_or_create(name: 'Italian', category_id: language_category.id)
Subcategory.where(name: 'Other', category_id: language_category.id).first_or_create(name: 'Other', category_id: language_category.id)
